# This is a docker-compose image used for monitoring using Grafana with Promethius
# CloudWatch Namespaces
# https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-services-cloudwatch-metrics.html

#Exporters to use for Promethius:
#https://github.com/prometheus/cloudwatch_exporter
#https://github.com/Jimdo/aws-health-exporter

# Exporters list
#https://prometheus.io/docs/instrumenting/exporters/

# Doc: https://grafana.com/docs/loki/latest/setup/install/docker/
# Make sure the docker-compose.yml is similar to the command arguments using docker.
version: '3'

networks:
  monitoring:
# Define persistent data volumes for each container
volumes:
  prometheus-data:
    driver: local
  grafana-data-lib:
    driver: local
  grafana-data-etc:
    driver: local

# Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data-lib:/var/lib/grafana
      - grafana-data-etc:/etc/grafana
      # For AWS credintials
      - ~/.aws/credentials:/usr/share/grafana/.aws/credentials:ro
    restart: unless-stopped
    networks:
      - monitoring

# Pometheus
  Prometheus:
    image: ubuntu/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./Metrics/data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring

    #Prometheus Exporters / Agents
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring

# Loki 
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./Logging/loki:/mnt/config 
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - monitoring

  # Protmail agent
  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - ./Logging/promtail:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - monitoring